#!/usr/bin/env bash
# Fails a PR that bumps a version or touches a release artefact by hand.
# Versions and CHANGELOG.md only ever change via the Release PR workflow
# (.github/workflows/release-pr.yml); see docs/releasing.md.
#
# Usage: check-no-version-bump.sh <base-sha> <head-sha>
# Env:
#   PR_HEAD_REF  - the PR's head branch name. release/v* is exempt (the one
#                  place these artefacts are meant to change).
#
# Operates on the caller's cwd git repo; sourced by test-checks.sh (see
# check-fragment.sh).
set -euo pipefail

# shellcheck source=scripts/release/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# The three files whose version field changie's replacements: bump. (Cargo.lock
# is derived from Cargo.toml, so it isn't checked separately here.)
# Uses merge-base semantics throughout: what the PR branch itself did since it
# diverged, not what changed on base since (e.g. a release).

# diff_touches BASE HEAD PATHSPEC
diff_touches() {
  local touched
  touched=$(git diff --name-only "$1...$2" -- "$3")
  [ -n "$touched" ]
}

# version_at KIND REV PATH — empty if the file doesn't exist at REV.
version_at() {
  version_of "$1" git show "${2}:${3}"
}

# bumped KIND MERGE_BASE HEAD PATH
# True only when the file has a version at both revisions and it differs.
bumped() {
  local before after
  before=$(version_at "$1" "$2" "$4")
  after=$(version_at "$1" "$3" "$4")
  [ -n "$before" ] && [ -n "$after" ] && [ "$before" != "$after" ]
}

check_no_version_bump() {
  local base="$1" head="$2"
  local head_ref="${PR_HEAD_REF:-}"

  if pr_head_is_release_branch "$head_ref"; then
    echo "ok: release branch ($head_ref) is where these artefacts are meant to change"
    return 0
  fi
  if ! changie_config_exists_at "$base"; then
    echo "ok: bootstrap (.changie.yaml doesn't exist at base) - this PR introduces the changelog system"
    return 0
  fi

  local failed=0 merge_base
  merge_base=$(git merge-base "$base" "$head")

  if diff_touches "$base" "$head" 'CHANGELOG.md'; then
    echo "FAIL: this PR touches CHANGELOG.md. It is generated by 'changie merge' in the Release PR workflow - never edit it by hand." >&2
    failed=1
  fi
  if diff_touches "$base" "$head" '.changes/v*.md'; then
    echo "FAIL: this PR adds, modifies, or deletes a .changes/v*.md release-notes file. Those are written by 'changie batch' in the Release PR workflow." >&2
    failed=1
  fi

  local spec kind path
  for spec in "json:$PKG_JSON" "json:$TAURI_CONF" "cargo_toml:$CARGO_TOML"; do
    kind="${spec%%:*}"
    path="${spec#*:}"
    if bumped "$kind" "$merge_base" "$head" "$path"; then
      echo "FAIL: this PR changes the version in $path. Versions are bumped only by the Release PR workflow's changie 'replacements:' - never by hand in a normal PR." >&2
      failed=1
    fi
  done

  if [ "$failed" -eq 0 ]; then
    echo "ok: no release artefact was touched by hand"
    return 0
  fi
  return 1
}

main() {
  if [ "$#" -ne 2 ]; then
    echo "usage: check-no-version-bump.sh <base-sha> <head-sha>" >&2
    exit 1
  fi
  check_no_version_bump "$1" "$2"
}

if [ "${BUDGEBELL_RELEASE_CHECK_TEST:-0}" != "1" ]; then
  main "$@"
fi
